import { User, Game, Message, Connection } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    avatar: 'https://images.unsplash.com/photo-1758512867312-70bd41431cd6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    location: {
      city: 'Mumbai',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    sports: ['cricket', 'football'],
    experienceLevel: 'intermediate',
    role: 'player',
    bio: 'Passionate cricket player looking for weekend matches',
    joined: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    avatar: 'https://images.unsplash.com/photo-1761258772329-751d7fb43cff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    location: {
      city: 'Mumbai',
      latitude: 19.0820,
      longitude: 72.8820,
    },
    sports: ['badminton', 'tennis'],
    experienceLevel: 'advanced',
    role: 'coach',
    bio: 'Professional badminton coach with 10 years experience',
    joined: new Date('2023-11-20'),
  },
  {
    id: '3',
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    avatar: 'https://images.unsplash.com/photo-1593341646782-e0b495cff86d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    location: {
      city: 'Mumbai',
      latitude: 19.0730,
      longitude: 72.8850,
    },
    sports: ['cricket', 'basketball'],
    experienceLevel: 'intermediate',
    role: 'player',
    bio: 'Love playing cricket on weekends!',
    joined: new Date('2024-02-10'),
  },
  {
    id: '4',
    name: 'Emma Davis',
    email: 'emma@example.com',
    avatar: 'https://images.unsplash.com/photo-1615022075479-6806a7713570?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    location: {
      city: 'Bangalore',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    sports: ['football', 'volleyball'],
    experienceLevel: 'beginner',
    role: 'player',
    bio: 'New to football, eager to learn!',
    joined: new Date('2024-03-05'),
  },
  {
    id: '5',
    name: 'Michael Chen',
    email: 'michael@example.com',
    avatar: 'https://images.unsplash.com/photo-1722087642932-9b070e9a066e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    location: {
      city: 'Mumbai',
      latitude: 19.0800,
      longitude: 72.8750,
    },
    sports: ['badminton'],
    experienceLevel: 'advanced',
    role: 'player',
    bio: 'Badminton enthusiast and tournament player',
    joined: new Date('2024-01-20'),
  },
  {
    id: '6',
    name: 'Priya Patel',
    email: 'priya@example.com',
    avatar: 'https://images.unsplash.com/photo-1633672267906-57dc7b0da6f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    location: {
      city: 'Mumbai',
      latitude: 19.0690,
      longitude: 72.8800,
    },
    sports: ['basketball', 'volleyball'],
    experienceLevel: 'intermediate',
    role: 'player',
    bio: 'Basketball player looking for pickup games',
    joined: new Date('2023-12-10'),
  },
];

export const mockGames: Game[] = [
  {
    id: 'g1',
    title: 'Weekend Cricket Match',
    sport: 'cricket',
    description: 'Friendly cricket match at Oval Maidan. All skill levels welcome!',
    creatorId: '1',
    location: {
      name: 'Oval Maidan, Mumbai',
      latitude: 18.9270,
      longitude: 72.8239,
    },
    dateTime: new Date('2026-02-22T10:00:00'),
    maxParticipants: 22,
    participants: ['1', '3'],
    experienceLevel: 'intermediate',
  },
  {
    id: 'g2',
    title: 'Badminton Coaching Session',
    sport: 'badminton',
    description: 'Free coaching session for beginners. Bring your own racket!',
    creatorId: '2',
    location: {
      name: 'Sports Complex, Andheri',
      latitude: 19.1136,
      longitude: 72.8697,
    },
    dateTime: new Date('2026-02-20T17:00:00'),
    maxParticipants: 10,
    participants: ['2', '5'],
    experienceLevel: 'beginner',
  },
  {
    id: 'g3',
    title: 'Evening Football Game',
    sport: 'football',
    description: '5v5 football match. Need more players!',
    creatorId: '4',
    location: {
      name: 'Cooperage Ground, Mumbai',
      latitude: 18.9220,
      longitude: 72.8235,
    },
    dateTime: new Date('2026-02-21T18:30:00'),
    maxParticipants: 10,
    participants: ['4', '1'],
    experienceLevel: 'intermediate',
  },
  {
    id: 'g4',
    title: 'Basketball Pickup Game',
    sport: 'basketball',
    description: 'Casual basketball game at local court',
    creatorId: '6',
    location: {
      name: 'Shivaji Park, Mumbai',
      latitude: 19.0282,
      longitude: 72.8397,
    },
    dateTime: new Date('2026-02-23T09:00:00'),
    maxParticipants: 10,
    participants: ['6', '3'],
    experienceLevel: 'intermediate',
  },
];

export const mockConnections: Connection[] = [
  {
    id: 'c1',
    fromUserId: '1',
    toUserId: '3',
    status: 'accepted',
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'c2',
    fromUserId: '1',
    toUserId: '5',
    status: 'pending',
    createdAt: new Date('2024-02-17'),
  },
  {
    id: 'c3',
    fromUserId: '2',
    toUserId: '1',
    status: 'accepted',
    createdAt: new Date('2024-02-10'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'm1',
    fromUserId: '3',
    toUserId: '1',
    content: 'Hey! Are you up for cricket this weekend?',
    timestamp: new Date('2026-02-18T10:30:00'),
    read: true,
  },
  {
    id: 'm2',
    fromUserId: '1',
    toUserId: '3',
    content: 'Yes! I created an event for Saturday morning.',
    timestamp: new Date('2026-02-18T10:35:00'),
    read: true,
  },
  {
    id: 'm3',
    fromUserId: '2',
    toUserId: '1',
    content: 'Hi Alex! I noticed you play cricket. Would you be interested in some fitness coaching?',
    timestamp: new Date('2026-02-18T14:20:00'),
    read: false,
  },
];

// Current logged in user
export const currentUser = mockUsers[0];
